name: "Acceptance Tests"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  Acceptance:
    name: "CentOS-7, puppet7-nightly"
    runs-on: macos-10.15
    strategy:
      fail-fast: false

    steps:
    - name: Install docker
      run: |
        mkdir -p ~/.docker/machine/cache
        curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
        brew install docker docker-machine
        docker-machine create --driver virtualbox default
        docker-machine env default

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Activate Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true

    - name: Provision test environment
      run: |
        eval $(docker-machine env default)
        bundle exec rake 'litmus:provision_list[acceptance]'
        echo ::group::=== REQUEST ===
        cat request.json || true
        echo
        echo ::endgroup::
        echo ::group::=== INVENTORY ===
        if [ -f 'spec/fixtures/litmus_inventory.yaml' ];
        then
          FILE='spec/fixtures/litmus_inventory.yaml'
        elif [ -f 'inventory.yaml' ];
        then
          FILE='inventory.yaml'
        fi
        sed -e 's/password: .*/password: "[redacted]"/' < $FILE || true
        echo ::endgroup::

    - name: docker ps
      run: |
        eval $(docker-machine env default)
        docker ps

    - name: Install agent
      run: |
        eval $(docker-machine env default)
        bundle exec rake 'litmus:install_agent[puppet7]'

    - name: Install module
      run: |
        eval $(docker-machine env default)
        bundle exec rake 'litmus:install_module'

    - name: Run acceptance tests
      run: |
        eval $(docker-machine env default)
        bundle exec rake 'litmus:acceptance:parallel'

    - name: Remove test environment
      if: ${{ always() }}
      continue-on-error: true
      run: |
        if [[ -f inventory.yaml || -f spec/fixtures/litmus_inventory.yaml ]]; then
          eval $(docker-machine env default)
          bundle exec rake 'litmus:tear_down'
          echo ::group::=== REQUEST ===
          cat request.json || true
          echo
          echo ::endgroup::
        fi
